### PR TITLE
Rename deprecated options

### LINKED ISSUE #50: hastPlugins, mdPlugins options have been deprecated
I am getting a bunch of these errors after upgrading to `mdx-loader@3.0.0`:

```
@mdx-js/mdx: The hastPlugins option has been deprecated in favor of rehypePlugins
                   Support for hastPlugins will be removed in MDX v2

@mdx-js/mdx: The mdPlugins option has been deprecated in favor of remarkPlugins
                   Support for mdPlugins will be removed in MDX v2
```

### PR DESCRIPTION
**Pull request by helfi92**
Fixes https://github.com/frontarm/mdx-util/issues/50.

### CODE REVIEW

**Comment by jamesknelson** [comment]
Thanks for this. Should have picked up on that earlier 😅

**Comment by helfi92** [comment]
No worries. The only other thing I'm trying to figure out is why migrating is no longer picking up my custom styles on DOM elements injected via the `components` prop.

**Comment by jamesknelson** [comment]
I'm not sure what the issue could be there. It could be a breaking change between the underlying mdx versions, but if you can isolate it to something here let me know and I'll push out another version.

Btw, just pushed out 3.0.2 with this change.

**Comment by helfi92** [comment]
From https://www.npmjs.com/package/@mdx-js/react#usage, `MDXProvider` seems to be imported from `@mdx-js/react` which seems to take the `components` prop but I don't see it imported in https://github.com/frontarm/mdx-util/blob/d236b4a805e5cfc656b6851a0e707a9d26cf0d29/packages/mdx-loader/index.js#L48

Should it be imported?

> Btw, just pushed out 3.0.2 with this change.

Many thanks!

**Comment by jamesknelson** [comment]
AFAIK, the loader shouldn't need to import `MDXProvider` -- that's something extra you can import if you need it.

**Comment by helfi92** [comment]
Ah, I figured it out. Before the migration, I used  to import as such:

```jsx
const { default: Page } = import(// .md file);
const components = {
  // ... 
};

// ...

render() {
  return (
    <Page components={components} />
  );
}
```

After migration, in order to apply the styles, I have to do:

```jsx
import { MDXProvider } from '@mdx-js/react';

const { default: Page } = import(// .md file);
const components = {
  // ... 
};

// ...

render() {
  return (
    <MDXProvider components={components}>
         <Page />
    </MDXProvider>
  );
}
```

**Pull request merged**
