### PR TITLE
Upgrade to @mdx-js/mdx v. 1

### PR DESCRIPTION
**Pull request by adueck**
This will fix issues #47 and #45.

Needed to include [https://www.npmjs.com/package/@mdx-js/react](@mdx-js/react) for things to work because of breaking changes in @mdx-js/mdx v. 1

### CODE REVIEW

**Comment by jamesknelson** [comment]
Thanks for this! One more request: could you remove the dependency on `@mdx-js/tag` from both files? As I understand it, it's no longer needed for version 1.

**Comment by adueck** [comment]
No prob. Glad I could help out with this awesome thing which was just what I needed! 😃 

You're right, `@mdx-js/tag` is no longer needed, I just tested and it works great without it.

**Comment by jamesknelson** [comment]
Published as 3.0.0 🎉

Thanks for your work on this!

**Comment by adueck** [comment]
Glad to help out! Might also want to upgrade `mdx.macro` in the same way? 🤔

**Comment by jamesknelson** [comment]
Just had an attempt at this in the mdx-macro--1 branch, although it appears that the whole transform would need to be rewritten from scratch.

Given that mdx.macro doesn't really work anyway (it doesn't handle auto-reload due to a limitation in babel-plugin-macros), I'm going to skip it for now. Would be happy to accept another PR though.

**Comment by adueck** [comment]
Ya using this instead of `mdx.macro` is definately the way to go. (Working without live reloading would be awful...) I'm gonna put in a PR to suggest mentioning the mdx-loader in the [mdx docs section on using mdx with creat-react-app](https://mdxjs.com/getting-started/create-react-app). Best solution hands down I think.

**Pull request merged**
